version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: employee
    ports:
      - 5432:5432

  admin:
    image: adminer
    restart: always
    ports:
      - "8282:8080"